#!/usr/bin/env bash

function config_opener(){
    local config_path=$1
    local program=$2
    local session_name=$3
    local title=$4
    (alacritty -T "$title" -e zsh -c "tmux new-session -s '${session_name}' -c ${config_path} '${program}'" &) &>/dev/null
}

function tui_opener(){
    local program=$1
    local title=$2
    (alacritty --config-file ~/.config/alacritty/alacritty-floating.toml -T "$title" -e sh -c "${program}" &) &>/dev/null
    # ( alacritty -T "$title" -e zsh -c "tmux new-session -s '${session_name}' -c '${config_path}' '${program}'; exec zsh -i" & ) &>/dev/null

}

function tui_opener_norm(){
    local program=$1
    local title=$2
    alacritty -e zsh -c "${program}" -T "$title"
}

function nconfig(){
    config_opener "~/.config/nvim" "nvim" "nvim-config"
}

function note(){
    config_opener "~/note" "nvim" "note"
}

function hyprconfig(){
    config_opener "~/.config/hypr" "nvim" "hypr-config"
}

function exovita_doc(){
    config_opener "/run/media/nico/nova/ctf-site/Documentation" "nvim" "exovita-doc"
}

function sec_controller(){
    tui_opener "python -u /home/nico/.config/LSD/sec-controller.py" "god-controller"
}

function open_nmtui(){
    tui_opener 'nmtui' 'nmtui'
}

case "$1"
in
    nconfig)
        nconfig
        ;;
    note)
        note
        ;;
    hyprconfig)
        hyprconfig
        ;;
    opennmtui)
        open_nmtui
        ;;
    exovitadoc)
        exovita_doc
        ;;
    secontroller)
        sec_controller
        ;;
    *)
        echo -e "\033[38;5;9mInvalid Input\033[0m"
        ;;
esac
